import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import Navbar from "@/components/nav/navbar";

export const metadata = {
  title: "Dental - Find Best Hospitals, Doctors, and Treatments, Alshifa Healthcare services.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
